[package]
name = "yquery"
version = "0.1.0"
authors = ["Mads Ravn <madsravn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

yaml-rust = "0.4"
pest = "2.1.3"
pest_derive = "2.1.0"
